#!/bin/bash

BASE="$HOME/cs350-os161"
CODE="$BASE/os161-1.99"
BUILD="$BASE/root"
LOGS="$BASE/logs"
LAST_LOG="$LOGS/.last_log"
ANO_FILE="$BASE/.ano"
LOOP_FILE="$BASE/.loop"
DO_FILE="$BASE/.do"
DEBUG_SLEEP=1

function set-last-log {
	touch $LAST_LOG
	ln -sf $1 $LAST_LOG
}

function make-kernel {
	log_file="/tmp/make_kernel_$(date +%s).log"
	echo -ne "Making Kernel...\r"
	cd $CODE/kern/conf
	./config ASST$ano >> $log_file
	cd ../compile/ASST$ano
	bmake depend >> $log_file
	bmake >> $log_file
	bmake install >> $log_file
	
	cat $log_file | tail -20 | grep 'Stop.' &>/dev/null
	if [ $? -eq 0 ]; then
		echo
		echo "Make failed"
		exit 1;
	else
		echo "Make successful!"
	fi
}

function make-user {
	log_file="/tmp/make_user_$(date +%s).log"
	echo -ne "Making User Programs...\r"
	cd $CODE
	bmake >> $log_file
	bmake install >> $log_file

	cat $log_file | tail -20 | grep 'Stop.' &>/dev/null
	if [ $? -eq 0 ]; then
		echo
		echo "Make failed"
		exit 1;
	else
		echo "Make successful!"
	fi
}

function debug-attach {
	clear
	printf "dir ../os161-1.99/kern/compile/ASST$ano\ntarget remote unix:.sockets/gdb" > /tmp/350gdbcommands
	cd $BUILD
	cs350-gdb -q $kernel_file --command=/tmp/350gdbcommands -tui
}

function debug {
	try-find-kernel
	tmux kill-session -t debug > /dev/null 2&>1
	tmux new-session -d -s debug -n run
	tmux send-keys -t debug:run "350 debug-wait" Enter
	tmux split-window -t debug -h
	tmux rename-window debugger
	tmux send-keys -t debug:debugger "sleep $DEBUG_SLEEP && 350 debug-attach" Enter
	tmux attach -t debug:debugger
}

function run {
	try-find-kernel
	cd $BUILD
	sys161 $1 $kernel_file
}

function set-do {
	vi $DO_FILE
}

function run-do {
	if [ ! -f $DO_FILE ]; then
		echo "No Do File found!"
		exit 1
	fi
	cd $BUILD
	sys161 $kernel_file "$(cat $DO_FILE)"
}

function loop {
	log_file="$LOGS/loop_$(date +%s)_$1.log"
	echo "Logging to $log_file"
	cd $BUILD
	try-find-kernel
	if [ ! -f $LOOP_FILE ]; then
		echo "No Loop File found!"
		exit 1
	fi
	counter=0
	loop_commands=$(cat $LOOP_FILE)
	echo
	echo "---- COMMANDS ----"
	echo $loop_commands
	echo "------------------"
	echo
	while [ $counter -lt $1 ]; do
		echo -ne "Iteration $((counter+1)) \r"
		echo ">>>>>>> ITERATION $((counter+1)) START <<<<<<<<" >> $log_file
		sys161 $kernel_file "$loop_commands" >> $log_file 2>&1
		echo ">>>>>>> ITERATION $((counter+1)) ENDED <<<<<<<<" >> $log_file
		echo >> $log_file
		let counter=counter+1
	done
	echo "Completed $1 Iterations"
	vi $log_file
}

function set-loop {
	vi $LOOP_FILE
}

function submit {
	cd $BASE
	if [ -f os161kern.tgz ]; then
		rm os161kern.tgz
		echo "Removing previous submission"
	fi
	echo "Submitting Assignment $ano to $1"
	log_file="$LOGS/submit_$ano_$(date +%s).log"
	echo "Logging to $log_file"
	/u/cs350/bin/cs350_submit $1 > $log_file 2>&1
	set-last-log $log_file
	vi $log_file
}

function set-ano {
	printf $1 > $ANO_FILE
	echo "Set Assignment Number to $(cat $ANO_FILE)"
}

function try-get-ano {
	if [ ! -f $ANO_FILE ]; then
		echo "No Assignment Number set!"
		exit 1
	fi
	ano=$(cat $ANO_FILE)
	kernel_file="$BUILD/kernel-ASST$ano"
}

function try-find-kernel {
	if [ ! -f $kernel_file ]; then
		echo "Kernel file not found. Did you make?"
		exit 1
	fi
}

function find-code {
	cd $CODE/kern
	egrep -Inir $1
}

function open {
	cd $CODE/kern
	filename=$1
	filepath=$(find -type f | grep -v ./compile/ | grep $filename | head -n1)
	if [ -z $filepath ]; then
		echo "$filename : No such file found"
		exit 1
	fi
	vi $filepath
}

function loop-debug {
	cd $BUILD
	if [ ! -f $kernel_file ]; then
		echo "Kernel file not found. Did you make?"
		exit 1
	elif [ ! -f $LOOP_FILE ]; then
		echo "No Loop File found!"
		exit 1
	fi
	loop_commands=$(cat $LOOP_FILE)
	echo
	echo "---- COMMANDS ----"
	echo $loop_commands
	echo "------------------"
	echo
	tmux kill-session -t debug > /dev/null 2>&1 
	tmux new-session -d -s debug -n run
	tmux send-keys -t debug:run "350 loop-debug-wait $1 && exit" Enter
	tmux split-window -t debug -h
	tmux rename-window debugger
	tmux send-keys -t debug:debugger "350 loop-debug-attach $1 && exit" Enter
	tmux attach -t debug:debugger
}

function loop-debug-wait {
	cd $BUILD
	loop_commands=$(cat $LOOP_FILE)
	for i in $(seq 1 $1); do
		clear
		echo ">>>>>>> ITERATION $i START <<<<<<<<"
		sys161 -w $kernel_file "$loop_commands"
		echo ">>>>>>> ITERATION $i ENDED <<<<<<<<"
		kill $(pgrep gdb -u $(whoami)) > /dev/null 2&>1
	done
}

function loop-debug-attach {
	cd $BUILD
	command_file="/tmp/350gdbcommands"
	printf "dir ../os161-1.99/kern/compile/ASST$ano\ntarget remote unix:.sockets/gdb\nb panic\nc" > $command_file
	loop_commands=$(cat $LOOP_FILE)
	for i in $(seq 1 $1); do
		sleep $DEBUG_SLEEP
		cs350-gdb -q $kernel_file -x $command_file -tui
	done
}

function help {
	echo "usage : 350 <command>"
	echo
	echo "Command List"
	echo -e "help\t\t\tShow this page"
	echo -e "set ano <num> \t\tSet Assignment Number to <num>"
	echo -e "set do\t\t\tSet commands that will run when using \"350 do\""
	echo -e "set loop\t\tSet commands that will run when using \"350 loop\""
	echo -e "ano\t\t\tShow Assignment Number"
	echo -e "loop <count>\t\tLoop <count> times"
	echo -e "loop -d <count>\t\tLoop <count> times. Attach to gdb on every iteration and break on panic"
	echo -e "run\t\t\tRun last compiled kernel"
	echo -e "make\t\t\tCompile kernel"
	echo -e "find <phrase>\t\tSearch all code for <phrase>"
	echo -e "open <pattern>\t\tVim into first filename that matches <pattern>"
	echo -e "do\t\t\tSimilar to run. Will automatically execute commands given via \"350 set do\""
	echo -e "make run\t\tMake + Run. If make fails, nothing happens."
	echo -e "make do\t\t\tMake + Do. If make fails, nothing happens."
	echo -e "debug\t\t\tRuns kernel and attaches debugger automatically (uses tmux)"
	echo -e "submit <target>\t\tSubmit Assignment to <target>. Similar to \"cs350_submit <target>\""
	echo -e "log\t\t\tVim into last log created"
	echo -e "log -o\t\t\tOutput last log created (useful for piping into grep)"
}

if ! [ -d $BASE ]; then
	echo "Cannot find $BASE. Is your base directory elsewhere?"
	exit 1
fi

if ! [ -d $LOGS ]; then
	echo "Making Logs directory at $LOGS"
	mkdir $LOGS
fi

if [ $# -lt 1 ]; then
	help
	exit 1
fi

if [ $1 = "help" ]; then
	help
	exit 0
fi

if [ $1 = "set" ]; then
	if [ $# -lt 2 ]; then
		echo "Set what?"
		exit 1
	elif [ $2 = "ano" ]; then
		if [ $# -lt 3 ]; then
			echo "Missing Assignment Number"
			exit 1
		fi
		set-ano $3
	elif [ $2 = "do" ]; then
		set-do
	elif [ $2 = "loop" ]; then
		set-loop
	fi
	exit 0
fi

try-get-ano

if [ $1 = "resume" ]; then
	resume
elif [ $1 = "ano" ]; then
	echo "Assignment Number : $ano"
elif [ $1 = "debug-attach" ]; then
	debug-attach
elif [ $1 = "make" ]; then
	make-kernel
	if [ "$2" = "run" ]; then
		echo -ne "\n"
		run
	elif [ "$2" = "do" ]; then
		echo -ne "\n"
		run-do
	elif [ "$2" = "user" ]; then
		echo -ne "\n"
		make-user
	fi
elif [ $1 = "run" ]; then
	run
elif [ $1 = "debug-wait" ]; then
	run -w
elif [ $1 = "debug" ]; then
	debug
elif [ $1 = "submit" ]; then
	if [ $# -ne 2 ]; then
		echo "Missing name?"
		exit 1
	fi
	submit $2
elif [ $1 = "do" ]; then
	run-do
elif [ $1 = "loop" ]; then
	if [ $2 = "-d" ]; then
		if [ $# -le 2 ]; then
			echo "Missing loop counter?"
			exit 1
		fi
		loop-debug $3
	else
		if [ $# -le 1 ]; then
			echo "Missing loop counter?"
			exit 1
		fi
		loop $2
	fi
elif [ $1 = "log" ]; then
	if [ ! -f $LAST_LOG ]; then
		echo "No Last Log found!"
		exit 1
	fi
	if [ "$2" = "-o" ]; then
		cat $LAST_LOG	
	else 
		vi $LAST_LOG
	fi
elif [ $1 = "find" ]; then
	if [ $# -le 1 ]; then
		echo "Find what?"
		exit 1
	fi
	find-code $2
elif [ $1 = "open" ]; then
	if [ $# -le 1 ]; then
		echo "Open what?"
		exit 1
	fi
	open $2
elif [ $1 = "loop-debug-wait" ]; then
	loop-debug-wait $2
elif [ $1 = "loop-debug-attach" ]; then
	loop-debug-attach $2
else		
	echo "Unknown Command : $1 $2 $3"
	help
	exit 1
fi
